---
title: ""
author: "Igo da Costa Andrade"

# Metadados
booktitle: "Equações Diferenciais Elementares e Problemas de Valores de Contorno"
booksubtitle: ""
bookauthors: "Boyce, W.; DiPrima, R. C."
bookaddres: "Rio de Janeiro"
bookpublisher: "LTC"
bookyear: "2020"
maincolor: "0065a5"
chaptertitle: "Introdução"
chapternumber: "1"

output: 
  bookdown::pdf_document2:
    template: template.tex
knit: >-
  (function(inputFile, encoding) {
    rmarkdown::render(
      input = inputFile,
      encoding = encoding,
      output_dir = file.path(dirname(inputFile), "../output"),
      output_format = "bookdown::pdf_document2"
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python("~/anaconda3/envs/science/bin/python")
```


\section*{PROBLEMAS}

Em cada um dos Problemas 1 a 4, desenhe um campo de direções para a equação diferencial dada. Baseado no campo de direções, determine o comportamento de $y$ quando $t \rightarrow \infty$. Se este comportamento depende o valor inicial de $y$ e $t = 0$, descreva essa dependência.

\begin{enumerate}
  \item $y^\prime = 3 - 2y$\\
  \iniSol
  Solução de equilíbrio: 
  \begin{align*}
    y^{\prime} (y^{*}) = 0 \Rightarrow 3 - 2y^{*} = 0 \Rightarrow y^{*} = \dfrac{3}{2}
  \end{align*}
  Como indica o campo de direções abaixo, $y \rightarrow y^{*} = \dfrac{3}{2}$ quando $t \rightarrow +\infty$, independente do valor inicial quando $t = 0$.
  \begin{center}
    \begin{tikzpicture}
      \def\yprime{3-2*y}
      \def\length{sqrt(1+(\yprime)^2)}
      \begin{axis}[
          view     = {0}{90},
          domain   = 0:4.5,
          y domain = 0:3,
          samples  = 12,
          xmax     = 5,
          ymax     = 3,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.2, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {3/2};
        \node[anchor=east] at (axis cs: 0, 3/2) {$\dfrac{3}{2}$};
      \end{axis}
    \end{tikzpicture}
  \end{center}
  \fimSol
  %%%% Fim do Problema 1
  \item $y^{\prime} = 2y - 3$\\
  \iniSol
  Solução de Equilíbrio:
  \begin{align*}
    y^{\prime} (y^{*}) = 0 \Rightarrow 2y^{*} - 3 = 0 \Rightarrow y^{*} = \dfrac{3}{2}
  \end{align*}
  Nesse caso, $y$ afasta-se da solução de equilíbrio, independentemente do valor inicial de $y$ quando $t = 0$. Como indica o campo de direções abaixo, $y \rightarrow -\infty$ para $y(t = 0) < \dfrac{3}{2}$ e $y \rightarrow +\infty$ para $y(t=0) > \dfrac{3}{2}$.
  
  \begin{center}
    \begin{tikzpicture}
      \def\yprime{2*y-3}
      \def\length{sqrt(1+(\yprime)^2)}
      \begin{axis}[
          view     = {0}{90},
          domain   = 0:4.5,
          y domain = 0:2.75,
          samples  = 12,
          xmax     = 5,
          ymax     = 3,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.2, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {3/2};
        \node[anchor=east] at (axis cs: 0, 3/2) {$\dfrac{3}{2}$};
      \end{axis}
    \end{tikzpicture}
  \end{center}
  \fimSol
  %%%% Fim do Problema 2
  \item $y^{\prime} = -1 - 2y$\\
  \iniSol
    Solução de Equilíbrio:
    \begin{align*}
      y^{\prime} (y^{*}) = 0 \Rightarrow -1 -2y^{*} = 0 \Rightarrow y^{*} = -\dfrac{1}{2}
    \end{align*}
    Como indica o campo de direções abaixo, todas as soluções tendem ao valor de equilíbrio $y^{*} = -\dfrac{1}{2}$ quando $t \rightarrow \infty$, independentemente do valor inicial quando $t = 0$.
    \begin{center}
      \begin{tikzpicture}
        \def\yprime{-1-2*y}
        \def\length{sqrt(1 +(\yprime)^2)}
        \begin{axis}[
          view      = {0}{90},
          domain    = 0:4.75,
          y domain  = -2:2,
          samples  = 12,
          xmax=5, ymax=2,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.2, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {-1/2};
        \node[anchor=east] at (axis cs: 0, -1/2) {$-\dfrac{1}{2}$};
        \end{axis}
      \end{tikzpicture}
    \end{center}
  \fimSol
  %%%% Fim do Problema 3
  \item $y^{\prime} = 1 + 2y$\\
  \iniSol
    Solução de Equilíbrio:
    \begin{align*}
      y^{\prime} (y^{*}) = 0 \Rightarrow 1 +2y^{*} = 0 \Rightarrow y^{*} = -\dfrac{1}{2}
    \end{align*}
    Nesse caso, $y$ afasta-se da solução de equilíbrio, independentemente do valor inicial de $y$ quando $t = 0$. Como indica o campo de direções abaixo, $y \rightarrow -\infty$ para $y(t = 0) < -\dfrac{1}{2}$ e $y \rightarrow +\infty$ para $y(t=0) > -\dfrac{1}{2}$.
    \begin{center}
      \begin{tikzpicture}
        \def\yprime{1+2*y}
        \def\length{sqrt(1 +(\yprime)^2)}
        \begin{axis}[
          view      = {0}{90},
          domain    = 0:4.75,
          y domain  = -2:1.75,
          samples  = 12,
          xmax=5, ymax=2,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.2, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {-1/2};
        \node[anchor=east] at (axis cs: 0, -1/2) {$-\dfrac{1}{2}$};
        \end{axis}
      \end{tikzpicture}
    \end{center}
  \fimSol
  %%%% Fim do Problema 4
\end{enumerate}

\noindent Em cada um dos Problemas 5 e 6, escreva uma equação diferencial da forma $dy/dt = ay + b$ cujas soluções têm o comportamento pedido quando $t \rightarrow \infty$.

\begin{enumerate}[resume]
  \item Todas as soluções se aproximam de $y = 2/3$.\\
  \iniSol
  Consideremos eqações diferenciais na forma $y^{\prime} = ay + b$. A solução de equilíbrio ($y^{*}$) é dada por:
  $$
  \dfrac{dy}{dt} (y^{*}) \equiv 0 \Rightarrow ay^{*} + b = 0 \Rightarrow y^{*} = -\dfrac{b}{a}
  $$
  Por outro lado, para determinarmos se as soluções aproximan-se ou afastam-se de $y^{*}$ quando $t \rightarrow \infty$, devemos observar o sinal de $\dfrac{d y^{\prime}}{dy}$ em $y^{*}$. Se $\dfrac{d y^{\prime}}{dy} (y^{*}) < 0$, as soluções tendem à solução de equilíbrio depois de um longo tempo. Caso, $\dfrac{d y^{\prime}}{dy} (y^{*}) > 0$, as soluções afastam-se.
  %%
  Portanto, para resolver o problema em questão, temos as seguintes condições:
  $$
  \begin{cases}
    y^{*} = -\dfrac{b}{a}\\
    \dfrac{d y^{\prime}}{dy} (y^{*}) = a < 0
  \end{cases}
  \Rightarrow 
  \begin{cases}
    \dfrac{b}{a} = -\dfrac{2}{3}\\
    a < 0
  \end{cases}
  \Rightarrow
  \begin{cases}
    b = -\dfrac{2}{3}a\\
    a < 0
  \end{cases}
  $$
  Fazendo $a = -3$ e $b = 2$, obtemos uma equação possível satisfazendo às condições acima: $$y^{\prime} = 2 - 3y$$
  O campo de direções pe mostrado abaixo:
      \begin{center}
      \begin{tikzpicture}
        \def\yprime{2-3*y}
        \def\length{sqrt(1 +(\yprime)^2)}
        \begin{axis}[
          view      = {0}{90},
          domain    = 0:4.75,
          y domain  = -1:2,
          samples  = 12,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.2, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {2/3};
        \node[anchor=east] at (axis cs: 0, 2/3) {$\dfrac{2}{3}$};
        \end{axis}
      \end{tikzpicture}
    \end{center}
  \fimSol
  %%%% Fim do Problema 5
  \item Todas as soluções se afastam de $y = 2$.\\
  \iniSol
  Nesse caso, devemos ter:
  $$
  \begin{cases}
    y^{*} = - \dfrac{b}{a} = 2\\
    \dfrac{d y^{\prime}}{dy} (y^{*}) = a > 0
  \end{cases}
  \Rightarrow 
  \begin{cases}
    \dfrac{b}{a} = -2\\
    a > 0
  \end{cases}
  \Rightarrow
  \begin{cases}
    b = -2a\\
    a > 0
  \end{cases}
  $$
  Uma equação possível satisfazendo às condições acima é $$y^{\prime} = -2 + y$$
  O campo de direções pe mostrado abaixo:
      \begin{center}
      \begin{tikzpicture}
        \def\yprime{-2+y}
        \def\length{sqrt(1 +(\yprime)^2)}
        \begin{axis}[
          view      = {0}{90},
          domain    = 0:4.75,
          y domain  = 0:4,
          samples  = 12,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.2, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {2};
        \end{axis}
      \end{tikzpicture}
    \end{center}
  \fimSol
  %%%% Fim do Problema 6
\end{enumerate}

\noindent Em cada um dos Problemas 7 a 19, desenhe um campo de direções para a equação diferencial dada. Baseado no campo de direções, determine o comportamento de $y$ quanto $t \rightarrow \infty$. Se esse comportamento depender do valor inicial de $y$ em $t = 0$, descreva essa dependência. Note que, nesses problemas, as equações diferenciais não são da forma $y^{\prime} =ay+b$, e o comportamento das soluções é um pouco mais complicado que o das soluções das equações do texto.

\begin{enumerate}[resume]
  \item $y^{\prime} = y (4 - y)$\\
  \iniSol
    Soluções de equilíbrio:
    \begin{align*}
      y^{\prime} (y^{*}) = 0 \Rightarrow y (4 - y) = 0 \Rightarrow
      \begin{cases}
        y = 0\\
        4 - y = 0 
      \end{cases}
      \Rightarrow
      \begin{cases}
        y^{*} = 0\\
        y^{*} = 4
      \end{cases}
    \end{align*}
      \begin{center}
      \begin{tikzpicture}
        \def\yprime{y*(4 - y)}
        \def\length{sqrt(1 +(\yprime)^2)}
        \begin{axis}[
          view      = {0}{90},
          domain    = 0:4.75,
          y domain  = -1:6,
          samples  = 12,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.3, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {0};
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {4};
        \end{axis}
      \end{tikzpicture}
    \end{center}
    A solução $y^{*} = 0$ é instável, no sentido que para condições iniciais próximas, as soluções para afastam-se dela com o passar do tempo. Por outro lado, a solução $y^{*} = 4$ é estável, ou seja, soluções pŕoximas de $y^{*}$ tendem para ela após algum tempo. Observando o campo de direções acima, concluímos que:
    \begin{itemize}
      \item Para $y(t = 0) < 0$ , as as soluções tendem a $-\infty$;
      \item Para $0 < y(t=0) < 4$, as soluções afastam-se de $y = 0$ e crescem, aproximando-se de $y = 4$;
      \item Para $y(t = 0) 4 0$, as soluções decrescem, aprosimando-se de $y = 4$.
    \end{itemize}
  \fimSol
  %%%% Fim do Problema 7
  \item $y^{\prime} = -y (5 - y)$\\
  \iniSol
    Soluções de equilíbrio:
    \begin{align*}
      y^{\prime} (y^{*}) = 0 \Rightarrow -y (5 - y) = 0 \Rightarrow
      \begin{cases}
        y = 0\\
        5 - y = 0 
      \end{cases}
      \Rightarrow
      \begin{cases}
        y^{*} = 0\\
        y^{*} = 5
      \end{cases}
    \end{align*}
      \begin{center}
      \begin{tikzpicture}
        \def\yprime{-y*(5 - y)}
        \def\length{sqrt(1 +(\yprime)^2)}
        \begin{axis}[
          view      = {0}{90},
          domain    = 0:4.75,
          y domain  = -1:7,
          samples  = 12,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.3, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {0};
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {5};
        \node[anchor=east] at (axis cs: 0, 5) {$5$};
        \end{axis}
      \end{tikzpicture}
    \end{center}
    A solução de equilíbrio $y^{*} = 0$ é estável enquanto $y^{*} = 5$ é instável. Observando o campo de direções acima, concluímos que:
    \begin{itemize}
      \item Para $y(t = 0) < 0$ , as as soluções crescem, aproximando-se de $y^{*} = 0$;
      \item Para $0 < y(t=0) < 5$, as soluções afastam-se de $y = 5$ e diminuem, aproximando-se de $y^{*} = 0$;
      \item Para $y(t = 0) > 5$, as soluções crescem indefinidamente.
    \end{itemize}
  \fimSol
  %%%% Fim do Problema 8
  \newpage
  \item $y^{\prime} = y^2$\\
  \iniSol
    Soluções de equilíbrio:
    \begin{align*}
      y^{\prime} (y^{*}) = 0 \Rightarrow y^2 = 0 \Rightarrow y^{*} = 0
    \end{align*}
      \begin{center}
      \begin{tikzpicture}
        \def\yprime{y^2}
        \def\length{sqrt(1 +(\yprime)^2)}
        \begin{axis}[
          view      = {0}{90},
          domain    = 0:4.75,
          y domain  = -3:3,
          samples  = 12,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.3, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {0};
        \end{axis}
      \end{tikzpicture}
    \end{center}
    Para $y(t = 0) < y^{*} = 0$, as soluções crescem aprosimando-se desta solução de equilíbrio. Por outro lado, para $y(t = 0) > y^{*} = 0$, as soluções afastam-se da solução de equilíbrio, crescendo indefinidamente.
  \fimSol
  %%%% Fim do Problema 9
  \item $y^{\prime} = y (y - 2)^2$\\
  \iniSol
    Soluções de equilíbrio:
    \begin{align*}
      y^{\prime} (y^{*}) = 0 \Rightarrow y (y - 2)^2 = 0 \Rightarrow
      \begin{cases}
        y = 0\\
        y - 2 = 0 
      \end{cases}
      \Rightarrow
      \begin{cases}
        y^{*} = 0\\
        y^{*} = 2
      \end{cases}
    \end{align*}
      \begin{center}
      \begin{tikzpicture}
        \def\yprime{y*(y - 2)^2}
        \def\length{sqrt(1 +(\yprime)^2)}
        \begin{axis}[
          view      = {0}{90},
          domain    = 0:4.75,
          y domain  = -1:4,
          samples  = 12,
          xlabel=$y$, ylabel=$y^{\prime}$,
          clip=false
        ]
        \addplot3 [mainColor!50, quiver={u={(1/\length)}, v={(\yprime)/(\length)}, scale arrows=0.3, every arrow/.append style={-latex}}] (x,y,0);
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {0};
        \addplot[mainColor, samples=5, ultra thick, no markers, domain=0:5] {2};
        \node[anchor=east] at (axis cs: 0, 5) {$5$};
        \end{axis}
      \end{tikzpicture}
    \end{center}
    Observando o campo de direções acima, concluímos que:
    \begin{itemize}
      \item Para $y(t = 0) < 0$ , as as soluções decrescem indefinidamente, afastando-se de $y^{*} = 0$;
      \item Para $0 < y(t=0) < 2$, as soluções afastam-se de $y = 0$ e crescem, aproximando-se de $y^{*} = 2$;
      \item Para $y(t = 0) > 2$, as soluções crescem indefinidamente.
    \end{itemize}
  \fimSol
  %%%% Fim do Problema 10
\end{enumerate}


